//! The general pasteboard, borrowed for a paste and given back. Talkr saves every item and type
//! the user had, puts the dictated text there marked transient and concealed (the
//! nspasteboard.org convention clipboard managers follow, so it stays out of their history), and
//! afterwards restores the user's content, unless they copied something new in the meantime.

use objc2::rc::{autoreleasepool, Retained};
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardWriting};
use objc2_foundation::{NSArray, NSData, NSString};

/// Saving more than this is skipped (a huge image copied in an editor): the paste still works,
/// but that content is not restored.
const MAX_SAVED_BYTES: usize = 64 * 1024 * 1024;
const PLAIN_TEXT: &str = "public.utf8-plain-text";
/// Markers for clipboard managers: not worth keeping, and private.
const MARKERS: &[&str] = &["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType"];

/// The user's pasteboard content, saved to put back after a paste: each item's types and data.
pub struct Saved {
    items: Vec<Vec<(String, Vec<u8>)>>,
    complete: bool,
}

fn general() -> Retained<NSPasteboard> {
    NSPasteboard::generalPasteboard()
}

/// Save everything on the pasteboard.
pub fn save() -> Saved {
    autoreleasepool(|_| {
        let mut items = Vec::new();
        let mut total = 0usize;
        let mut complete = true;
        'items: for item in general().pasteboardItems().map(|list| list.to_vec()).unwrap_or_default() {
            let mut types = Vec::new();
            for kind in item.types().to_vec() {
                // Reading renders data an app promised lazily; a type it cannot render is skipped.
                let Some(data) = item.dataForType(&kind) else { continue };
                if total + data.len() > MAX_SAVED_BYTES {
                    complete = false;
                    log::info!("clipboard content is too large to keep while pasting; it will not be restored");
                    break 'items;
                }
                total += data.len();
                types.push((kind.to_string(), data.to_vec()));
            }
            items.push(types);
        }
        Saved { items, complete }
    })
}

fn write(items: Vec<Retained<NSPasteboardItem>>) -> Option<isize> {
    let pasteboard = general();
    pasteboard.clearContents();
    if !items.is_empty() {
        let objects: Vec<_> = items.into_iter().map(ProtocolObject::<dyn NSPasteboardWriting>::from_retained).collect();
        if !pasteboard.writeObjects(&NSArray::from_retained_slice(&objects)) {
            return None;
        }
    }
    Some(pasteboard.changeCount())
}

fn mark(item: &NSPasteboardItem) {
    let empty = NSData::with_bytes(&[]);
    for marker in MARKERS {
        item.setData_forType(&empty, &NSString::from_str(marker));
    }
}

/// Put `text` on the pasteboard as plain text; `transient` keeps it out of clipboard managers.
/// Returns the pasteboard's change count afterwards, which moves as soon as anyone else writes.
pub fn put_text(text: &str, transient: bool) -> Option<isize> {
    autoreleasepool(|_| {
        let item = NSPasteboardItem::new();
        if !item.setString_forType(&NSString::from_str(text), &NSString::from_str(PLAIN_TEXT)) {
            return None;
        }
        if transient {
            mark(&item);
        }
        write(vec![item])
    })
}

/// The pasteboard's change count right now.
pub fn change_count() -> isize {
    autoreleasepool(|_| general().changeCount())
}

/// Put the saved content back, unless the pasteboard changed since `count` (the user copied
/// something new, which must win). Returns whether it was restored.
pub fn restore(saved: Saved, count: isize) -> bool {
    if change_count() != count {
        log::info!("the clipboard changed during the paste; leaving the new content");
        return false;
    }
    if !saved.complete {
        return false;
    }
    autoreleasepool(|_| {
        let items = saved
            .items
            .iter()
            .map(|types| {
                let item = NSPasteboardItem::new();
                for (kind, bytes) in types {
                    item.setData_forType(&NSData::with_bytes(bytes), &NSString::from_str(kind));
                }
                // Restoring is not a new copy: keep it out of clipboard history too.
                mark(&item);
                item
            })
            .collect();
        write(items).is_some()
    })
}

/// Tests that use the real pasteboard, post keys or move focus take turns.
#[cfg(test)]
pub static TEST_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// The plain text on the pasteboard, if any.
#[cfg(test)]
pub fn text() -> Option<String> {
    autoreleasepool(|_| general().stringForType(&NSString::from_str(PLAIN_TEXT)).map(|s| s.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The real pasteboard: save, borrow and restore, then put back what the machine had. Runs on
    /// CI only, so a developer's clipboard is never borrowed by `cargo test`.
    #[test]
    fn borrowing_the_pasteboard_gives_it_back() {
        if std::env::var_os("CI").is_none() {
            return;
        }
        let _turn = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let original = save();
        let Some(user) = put_text("the user's clipboard", false) else { return };
        assert_eq!(text().as_deref(), Some("the user's clipboard"));
        let saved = save();
        assert_eq!(change_count(), user);
        let Some(ours) = put_text("dictated text", true) else { return };
        assert_ne!(ours, user);
        assert_eq!(text().as_deref(), Some("dictated text"));
        assert!(restore(saved, ours));
        assert_eq!(text().as_deref(), Some("the user's clipboard"));

        // A copy made during the paste wins.
        let saved = save();
        let ours = put_text("dictated text", true).unwrap();
        put_text("copied meanwhile", false).unwrap();
        assert!(!restore(saved, ours));
        assert_eq!(text().as_deref(), Some("copied meanwhile"));

        restore(original, change_count());
    }
}
